### ISSUE TITLE
USER STORY: Log in and out

### ISSUE THREAD

**Issue by TheresLundqvist** [TheresLundqvist/Your-area#1]
As a **Site User** I can **log in and out of my account** so that **I can keep my account secure**.

### **Acceptance Criteria**  
- Sign-in button visible in the nav bar.
- The login button redirects the user to a log-in page.
- User gets logged in after all details have been filled in and presses sign in button. 
- User receives a message when successfully logged in/logged out.
- If incorrect credentials are made, the user receives feedback on what was incorrectly entered.
- When log out button is clicked user should be asked to confirm action to log out.

### **Tasks**
- [x] Install allauth and add to installed apps
- [x] Add allauth urls
- [x] Add log in and log out links to navbar
- [x] Customise allauth login, logout HTML templates
- [x] Create success messages for successful login/logout
