### ISSUE TITLE
USER STORY: Sort products

### ISSUE THREAD

**Issue by TheresLundqvist** [TheresLundqvist/Your-area#10]
As a **Site user** I can **sort all products** so that **I can view products based on price or title**.

### **Acceptance Criteria**
- Inside the browse products page a sort products drop-down menu should be visable to the user.
- When the user clicks the drop-down arrow a list of pre-defined sort options should appear.
- When the user selects a sort option the page should display the products in that order.

### **Tasks**
- [x] Create sort selector on products page and add sort parameters to select box options
- [x] Add GET request to the all_products view to sort products
- [x] Write javascript to update product list when sort select box is changed
