### ISSUE TITLE
USER STORY: Order history

### ISSUE THREAD

**Issue by TheresLundqvist** [TheresLundqvist/Your-area#13]
As a **Site user** I can **view my order history** so that **I can keep track of my orders**.

### **Acceptance Criteria**
- In user profile they should see a list of their previous orders.
- As the user clicks on the order number they should see a detailed breakdown of the order by product.

### **Tasks**
- [x] Add the users profile to the order in the checkout success view
- [x] Update profile html template to include the order history
- [x] Link order number to checkout success html page
