### ISSUE TITLE
USER STORY: View order history

### ISSUE THREAD

**Issue by TheresLundqvist** [TheresLundqvist/Your-area#15]
As a **Site user** I can **view my order history** so that **I can remember what purchases I've made**

### **Acceptance Criteria**
- Logged in users should be able to click on their profile picture to view previous purchases.
- As they click on the order number they should see a detailed breakdown of the order by product.

### **Tasks**
- [x] Add the users profile to the order in the checkout success view
- [x] Update profile HTML template to include the order history
- [x] Link order number to checkout success html page
