### ISSUE TITLE
USER STORY: Add products to shopping cart

### ISSUE THREAD

**Issue by TheresLundqvist** [TheresLundqvist/Your-area#18]
As a **Site user** I can **add several products in different quantities to my shopping cart** so that **I can purchase them all together when I am ready**.

### **Acceptance Criteria**
- In the product detail page there should be a quantity selector and an "add to shopping cart" - button.
- As the user clicks on the "add to shopping cart" - button, the chosen quantity of the product should be added to the user's shopping cart.
- The user should be prevented from adding quantities outside the min/max threshold.

### **Tasks**
- [x] Create an "add to bag" form within the product_detail.html template.
- [x] Create add_to_bag view and URL.
- [x] Add bag content to context processor.
- [x] Add javascript to increase/decrease quantity in the bag.
- [x] Style "add to bag" - button and quantity selector.
