### ISSUE TITLE
USER STORY: Shopping cart running total

### ISSUE THREAD

**Issue by TheresLundqvist** [TheresLundqvist/Your-area#19]
As a **Site user**, I can **view a running total of my shopping cart as I am shopping** so that **I can see how much it costs in total**.

### **Acceptance Criteria**
- As the user adds products to their cart, a message should appear in the right-hand corner of the screen informing the user that the item has been added, giving them a snapshot of the cart contents and the total cost of the cart.

### **Tasks**
- [x] Create a toast HTML template for the success message.
- [x] Add success message to add to cart view.
- [x] Include the shopping cart running total in success HTML template.
