### ISSUE TITLE
USER STORY: Adjust product quantity

### ISSUE THREAD

**Issue by TheresLundqvist** [TheresLundqvist/Your-area#21]
As a **Site user** I can **adjust the quantity of individual products in my cart** so that **I can easily make changes before I purchase**.

### **Acceptance Criteria**
- When the user is viewing the shopping cart, they should be able to adjust the quantity of each product line item and update the subtotal.
- The user should be able to delete the product and the bag should be updated accordingly.

### **Tasks**
- [x] Add quantity selector buttons and update/delete buttons to the shopping cart page.
- [x] Write javascript to increase/decrease the quantity when the button is clicked
- [x] Write javascript to update the cart when the update button is clicked
- [x] Write javascript to delete the product line items when the delete button is clicked.
- [x] Create adjust_cart and delete_item views and urls
