### ISSUE TITLE
USER STORY: Payment details

### ISSUE THREAD

**Issue by TheresLundqvist** [TheresLundqvist/Your-area#22]
As a **Site user** I can **easily enter my payment information securely** so that **I can purchase my chosen products quickly with no issues**.

### **Acceptance Criteria**
- As the user navigates to the checkout page, they should see the stripe elements UI where they can enter their card details securely and pay for their order.
- The user should receive feedback if the card number is valid/invalid.

### **Tasks**
- [x] Utilising Stripe Elements, create a Credit Card Details section in the Order Form and embed the Stripe UI component.
- [x] Add custom styling to Stripe Elements.
- [x] Add Stripe code to Checkout view.
- [x] Include Stripe Javascript
- [x] Use Stripe Webhooks
