### ISSUE TITLE
USER STORY: View shopping cart

### ISSUE THREAD

**Issue by TheresLundqvist** [TheresLundqvist/Your-area#23]
As a **Site user** I can **view a the contents of my shopping cart at any time** so that **I can see what is included and the total cost**.

### **Acceptance Criteria**
- As the user clicks on the shopping bag icon in the nav bar they are taken to the shopping cart page.
- The shopping cart page should show the products the user added to their cart, unit price, quantity and subtotal.
- The user should be able to increase/decrease the quantity of items in the bag.
- The bag total, delivery costs and then the grand total are displayed at the bottom of the page.
- The user should have the option to checkout or to continue shopping.

### **Tasks**
- [x] Create bag app, HTML template and URL.
- [x] Create view_bag view
- [x] Add link to shopping bag to the navbar.
- [x] Create context.py in the bag app and add to settings.py.
- [x] Style bag.html page
