### ISSUE TITLE
USER STORY: Guest checkout

### ISSUE THREAD

**Issue by TheresLundqvist** [TheresLundqvist/Your-area#24]
As a **Site user** I can **checkout as a guest** so that **I don't have to sign up for an account**.

### **Acceptance Criteria**
- When the user clicks the secure checkout button in the shopping bag, they should see a checkout form and a summary of their order.
- The user can populate their details and choose to save their personal information by creating an account.
- When the user completes the form and presses submit their order should be completed.

### **Tasks**
- [x] Create checkout models
- [x] Create checkout form
- [x] Create checkout views
- [x] Install Django Crispy Forms
- [x] Create HTML templates for checkout.
