### ISSUE TITLE
USER STORY: Order confirmation

### ISSUE THREAD

**Issue by TheresLundqvist** [TheresLundqvist/Your-area#25]
As a **Site user** I can **view and recieve a order confirmation after checkout** so that **I know my purchase was successful**.

### **Acceptance Criteria**
- As the user submits the checkout form, they should be redirected to a checkout success page where they can see an order confirmation and a summary of their order.
- After the user submitted their order they should receive a email confirmation to the email address they entered in their order form.
- The confirmation email should contain all the details of the order.

### **Tasks**
- [x] Create Checkout Success view
- [x] Create Checkout Success HTML template an render order summary.
- [x] Create email templates for order confirmation
- [x] Update webhook handler to handle sending confirmation email
- [x] Set up Gmail to send emails
