### ISSUE TITLE
USER STORY: Product management

### ISSUE THREAD

**Issue by TheresLundqvist** [TheresLundqvist/Your-area#26]
As a **store owner** I can **add/edit/delete products through an easy-to-use interface** so that **I can manage the store's contents**.

### **Acceptance Criteria**
- As the site owner is logged in, a Your Area management option should appear in the user drop-down menu.
- As the site owner navigates to the Your Area management page they should see a user-friendly form where they can add a new product to the store.
- The site owner should also be able to add new products on the Your Area management page by clicking the 'Add Product' button at the top of the page.
- The site owner should be able to edit and delete products from both the main Your Area management page and also the product detail page.
- The add/edit forms should contain fields for all required information and should include form validation with helpful feedback if the form is invalid.
- The site owner should receive a success message when they have successfully added/edited/deleted a product.

### **Tasks**
- [x] Create product form.py
- [x] Create html pages for add product, edit product and confirm delete product.
- [x] Write add/edit/delete product views and include form validation
- [x] Include error/success messages to give feedback to the user
- [x] Add edit and delete buttons to product cards and product detail page
- [x] Create an "Add Product" button on Your Area management page.
- [x] Add "Your Area management" option to user dropdown menu of nav bar.
