### ISSUE TITLE
USER STORY: Newsletter signup

### ISSUE THREAD

**Issue by TheresLundqvist** [TheresLundqvist/Your-area#28]
As a **Site user** I can **sign up for the website's newsletter** so that **I can keep up to date with new products and promotions**.

### **Acceptance Criteria**
- The footer should contain a 'Newsletter' section where the user can input their email address to sign up.
- The user's email should be added to the mailchimp mailing list.

### **Tasks**
- [x] Create newsletter app
- [x] Update newsletter model
- [x] Add views and urls to newsletter app.
- [x] Add newsletter url to main app urls and settings
- [x] Style newsletter template
