### ISSUE TITLE
USER STORY: Approve user comments

### ISSUE THREAD

**Issue by TheresLundqvist** [TheresLundqvist/Your-area#29]
As a **Site owner** I can **approve comments** so that **no objectionable comments is shown**.

### **Acceptance Criteria**
- Show all new comments in admin page.
- Make comments visable on page only after approval from Admin

### **Tasks**
- [ ] Create comment model
- [ ] Create action approve_comments for Admin
- [ ] Add function so comment becomes visable after approval
