### ISSUE TITLE
USER STORY: Product review

### ISSUE THREAD

**Issue by TheresLundqvist** [TheresLundqvist/Your-area#30]
As a **Site user** I can **give products star ratings and comments** so that **other users can make a better assessment**.

### **Acceptance Criteria**
- Logged-in users can give products a star rating from 1-5 which adds to the product's viewable average rating
- Visible average rating for every product
- Site users can add rating and comment at the bottom in product detail page 
- Only logged in users can view rating and comment form and submit a rating/comment
- All users (logged-in or not) can view rating and approved comments in product detail
- The user name and creation date is viewable next to the comment
- Admin can view rating in admin panel

### **Tasks**
- [ ] Add font awesome star icon
- [ ] Function that generates average star rating
- [ ] Create comment and rating model
- [ ] Add function so comments appear only after admin approve
- [ ] Clickable star icon adds to the average counter
- [ ] Display star rating and comments in the admin panel
- [ ] Create comment form
