### ISSUE TITLE
USER STORY: Site declaration

### ISSUE THREAD

**Issue by TheresLundqvist** [TheresLundqvist/Your-area#31]
As a **Site user** I can **immediately understand the purpose of the site** so that **I can decide if it meets my needs**.

### **Acceptance Criteria**
- Home page declares site purpose with a inspiring photo and site declaration
- "Start shopping" - button next to site declaration which redirects user to product details

### **Tasks**
- [x] Declare site purpose
- [x] Shop now link next to declaration
- [x] Hero image with overlay text declaration
