### ISSUE TITLE
USER STORY: Register account

### ISSUE THREAD

**Issue by TheresLundqvist** [TheresLundqvist/Your-area#32]
As a **Site user** I can **register an account** so that **I can add/edit/delete comments I made**.

### **Acceptance Criteria**
- The sign up button is visable on home page
- User is redirected from sign up link to a sign up page
- Add sign up fields for name, email, password and password verification and button that submits the users request to sign up
- User receives a success message after submission of sign up form, that the sign up was successful.

### **Tasks**
- [ ] Create sign up button that redirects user to sign up page.
- [ ] Add allauth sign up.
- [ ] Style sign up page to match Your Area styling.
