### ISSUE TITLE
USER STORY: Register account

### ISSUE THREAD

**Issue by TheresLundqvist** [TheresLundqvist/Your-area#4]
As a **Site user** I can **register a account** so that **I can have a personal account**.

### **Acceptance Criteria**
- A signup link should be visible in the navbar.
- User is redirected to the signup page from sign up link.
- After the user clicks the confirm button, a new account is created.
- Success message pops up when account is created to give feedback to user.

### **Tasks**
- [x]  Install allauth and add to installed apps
- [x] Add allauth urls
- [x] Add signup link to navbar
- [x] Customise allauth signup form HTML templates
- [x] Create message to notify user of successful signup
