### ISSUE TITLE
USER STORY: Product list view

### ISSUE THREAD

**Issue by TheresLundqvist** [TheresLundqvist/Your-area#6]
As a **Site user** I can **view a list of products** so that **I can select a product to view**.

### **Acceptance Criteria**
- The individual products should appear as cards showing the product image, name and price.
- When the user clicks on a product they should be taken to the full product details.

### **Tasks**
- [x] Create Product Model.
- [x] Create all_products view in views.py to list all products in database.
- [x] Develop a user-friendly product card layout using bootstrap cards and make it responsive.
- [x] Link product cards to product detail page.
