### ISSUE TITLE
USER STORY: Product category

### ISSUE THREAD

**Issue by TheresLundqvist** [TheresLundqvist/Your-area#8]
As a **Site user** I can **view a specific category of products** so that **I can browse the type of products I'm looking for**.

### **Acceptance Criteria**
- Diffrent categorys displayed in navbar for furniture, lights, interior etc
- As the user clicks on a particular category the products with that category label should display on the page.

### **Tasks**
- [x] Create Category Model in products app and link to product model as a foreign key
- [x] Create the categories in the admin panel
- [x] Add category parameters to product urls in main_nav.html
- [x] Write GET request logic in all_products view to filter products by category
